<a href="https://colab.research.google.com/github/dondreojordan/DS-Unit-2-Linear-Models/blob/master/module4-logistic-regression/LS_DS_214_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment ðŸŒ¯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [ ]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [ ]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [ ]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [ ]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [ ]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [ ]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [ ]:
df.isnull().sum()

Burrito             0
Date                0
Yelp              334
Google            334
Chips             395
Cost                7
Hunger              3
Mass (g)          399
Density (g/mL)    399
Length            138
Circum            140
Volume            140
Tortilla            0
Temp               20
Meat               14
Fillings            3
Meat:filling        9
Uniformity          2
Salsa              25
Synergy             2
Wrap                3
Unreliable        388
NonSD             414
Beef              242
Pico              263
Guac              267
Cheese            262
Fries             294
Sour cream        329
Pork              370
Chicken           400
Shrimp            400
Fish              415
Rice              385
Beans             386
Lettuce           410
Tomato            414
Bell peper        414
Carrots           420
Cabbage           413
Sauce             383
Salsa.1           414
Cilantro          406
Onion             404
Taquito           417
Pineapple         414
Ham               419
Chile relleno     417
Nopales           417
Lobster           420
Queso             421
Egg               416
Mushroom          418
Bacon             418
Sushi             419
Avocado           408
Corn              418
Zucchini          420
Great               0
dtype: int64

In [ ]:
df.columns

Index(['Burrito', 'Date', 'Yelp', 'Google', 'Chips', 'Cost', 'Hunger',
       'Mass (g)', 'Density (g/mL)', 'Length', 'Circum', 'Volume', 'Tortilla',
       'Temp', 'Meat', 'Fillings', 'Meat:filling', 'Uniformity', 'Salsa',
       'Synergy', 'Wrap', 'Unreliable', 'NonSD', 'Beef', 'Pico', 'Guac',
       'Cheese', 'Fries', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish',
       'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots',
       'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito',
       'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Queso',
       'Egg', 'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini',
       'Great'],
      dtype='object')

In [ ]:
 columns = ['Beef', 'Pico', 'Guac',
            'Cheese', 'Fries', 'Sour cream', 
            'Pork', 'Chicken', 'Shrimp', 
            'Fish','Rice', 'Beans', 
            'Lettuce', 'Tomato', 'Bell peper', 
            'Carrots','Cabbage', 'Sauce', 
            'Salsa.1', 'Cilantro', 'Onion', 
            'Taquito', 'Pineapple', 'Ham', 
            'Chile relleno', 'Nopales', 'Lobster',
            'Egg', 'Mushroom', 'Bacon', 
            'Sushi', 'Avocado', 'Corn', 'Zucchini']

In [ ]:
for c in columns:
  df[c] = df[c].str.replace('x', '1', case=False).astype(float)

In [ ]:
for c in columns:
  df[c] = df[c].fillna(0)

#1) Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.

In [ ]:
#Import
import datetime as dt

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], infer_datetime_format=True)
df['Year'] = df['Date'].dt.year
print(df.shape)
df.head()

(421, 60)

      Burrito       Date  Yelp  Google  ... Corn  Zucchini  Great  Year
0  California 2016-01-18   3.5     4.2  ...  0.0       0.0  False  2016
1  California 2016-01-24   3.5     3.3  ...  0.0       0.0  False  2016
2    Carnitas 2016-01-24   NaN     NaN  ...  0.0       0.0  False  2016
3       Asada 2016-01-24   NaN     NaN  ...  0.0       0.0  False  2016
4  California 2016-01-27   4.0     3.8  ...  0.0       0.0   True  2016

[5 rows x 60 columns]

In [ ]:
df['Beef'].value_counts()

0.0    242
1.0    179
Name: Beef, dtype: int64

In [ ]:
#Train is <=2016
train =df[df['Year'] <= 2016]
print(train.shape)
#Validate ==2017
val =df[df['Year'] == 2017]
print(val.shape)
#Test is >=2018
test =df[df['Year'] >= 2018]
print(test.shape)

# The sum of indeces of the shape of train, val, test == 421 == to auto_df.shape

(298, 60)
(85, 60)
(38, 60)

#2) Begin with baselines for classification. Target us 'Great' Column try get better accuracy then the baseline

In [ ]:
# All the imports
from sklearn.linear_model import LogisticRegressionCV
from sklearn.preprocessing import StandardScaler
from category_encoders import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
target = 'Great'
y_train = train[target]
y_train.value_counts(normalize=True)

False    0.590604
True     0.409396
Name: Great, dtype: float64

In [ ]:
'''Beat 0.59 for an accuracy score.'''

'Beat 0.59 for an accuracy score.'

In [ ]:
features = train.columns.drop([target] + ['Date'])
X_train = train[features]
y_train = train[target]
X_val = val[features]
y_val = val[target]
X_test = test[features]
y_test = test[target]

In [ ]:
# Check that training and validation contain all observations from X
assert df.shape[0] == X_train.shape[0] + X_val.shape[0] + X_test.shape[0]

In [ ]:
X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

((298, 58), (298,), (85, 58), (85,), (38, 58), (38,))

#3) Use scikit-learn for logistic regression.

In [ ]:
train

        Burrito       Date  Yelp  Google  ... Corn  Zucchini  Great  Year
0    California 2016-01-18   3.5     4.2  ...  0.0       0.0  False  2016
1    California 2016-01-24   3.5     3.3  ...  0.0       0.0  False  2016
2      Carnitas 2016-01-24   NaN     NaN  ...  0.0       0.0  False  2016
3         Asada 2016-01-24   NaN     NaN  ...  0.0       0.0  False  2016
4    California 2016-01-27   4.0     3.8  ...  0.0       0.0   True  2016
..          ...        ...   ...     ...  ...  ...       ...    ...   ...
296  California 2016-12-02   4.0     4.3  ...  0.0       0.0  False  2016
297       Other 2016-12-02   NaN     NaN  ...  0.0       0.0  False  2016
298  California 2016-12-10   3.5     3.7  ...  0.0       0.0  False  2016
299       Asada 2016-12-10   NaN     NaN  ...  0.0       0.0  False  2016
300       Other 2016-12-15   4.5     4.6  ...  0.0       0.0  False  2016

[298 rows x 60 columns]

In [ ]:
test

         Burrito       Date  Yelp  Google  ... Corn  Zucchini  Great  Year
77    California 2026-04-25   NaN     NaN  ...  0.0       0.0   True  2026
386   California 2018-01-02   NaN     NaN  ...  0.0       0.0  False  2018
387        Other 2018-01-09   4.5     3.8  ...  0.0       0.0  False  2018
388   California 2018-01-12   3.5     4.3  ...  0.0       0.0   True  2018
389        Other 2018-01-12   NaN     NaN  ...  0.0       0.0  False  2018
390        Asada 2018-04-04   NaN     NaN  ...  0.0       0.0   True  2018
391     Carnitas 2018-04-09   NaN     NaN  ...  0.0       0.0   True  2018
392     Carnitas 2018-04-09   NaN     NaN  ...  0.0       0.0   True  2018
393     Carnitas 2018-04-09   NaN     NaN  ...  0.0       0.0  False  2018
394   California 2018-04-14   NaN     NaN  ...  0.0       0.0   True  2018
395   California 2018-04-14   NaN     NaN  ...  0.0       0.0  False  2018
396        Other 2018-04-16   NaN     NaN  ...  0.0       0.0  False  2018
397        Other 2018-04-16   NaN     NaN  ...  0.0       0.0  False  2018
398     Carnitas 2018-04-20   NaN     NaN  ...  0.0       0.0   True  2018
399     Carnitas 2018-04-20   NaN     NaN  ...  0.0       0.0   True  2018
400   California 2018-04-21   3.5     3.8  ...  0.0       0.0   True  2018
401  Surf & Turf 2018-04-21   NaN     NaN  ...  0.0       0.0  False  2018
402   California 2018-04-29   NaN     NaN  ...  0.0       0.0  False  2018
403   California 2018-04-29   NaN     NaN  ...  0.0       0.0  False  2018
404   California 2018-05-01   NaN     NaN  ...  0.0       0.0  False  2018
405     Carnitas 2018-05-07   NaN     NaN  ...  0.0       0.0  False  2018
406     Carnitas 2018-05-07   NaN     NaN  ...  0.0       0.0   True  2018
407        Other 2018-05-22   NaN     NaN  ...  0.0       0.0   True  2018
408        Other 2018-05-22   NaN     NaN  ...  0.0       0.0   True  2018
409        Other 2018-05-22   NaN     NaN  ...  0.0       0.0   True  2018
410        Other 2018-05-22   NaN     NaN  ...  0.0       0.0  False  2018
411        Other 2018-05-22   NaN     NaN  ...  0.0       0.0  False  2018
412   California 2018-11-06   NaN     NaN  ...  0.0       0.0   True  2018
413   California 2019-08-24   NaN     NaN  ...  0.0       0.0   True  2019
414        Other 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019
415        Asada 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019
416        Other 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019
417   California 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019
418        Other 2019-08-27   NaN     NaN  ...  0.0       0.0  False  2019
419        Other 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019
420   California 2019-08-27   NaN     NaN  ...  0.0       0.0  False  2019
421        Other 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019
422        Other 2019-08-27   NaN     NaN  ...  0.0       0.0   True  2019

[38 rows x 60 columns]

In [ ]:
test['Great'] = (test['Great'] == True ).astype(int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
train.isnull().sum()

Burrito             0
Date                0
Yelp              227
Google            227
Chips             276
Cost                6
Hunger              1
Mass (g)          298
Density (g/mL)    298
Length            123
Circum            124
Volume            124
Tortilla            0
Temp               15
Meat               10
Fillings            1
Meat:filling        6
Uniformity          2
Salsa              20
Synergy             2
Wrap                2
Unreliable        271
NonSD             293
Beef                0
Pico                0
Guac                0
Cheese              0
Fries               0
Sour cream          0
Pork                0
Chicken             0
Shrimp              0
Fish                0
Rice                0
Beans               0
Lettuce             0
Tomato              0
Bell peper          0
Carrots             0
Cabbage             0
Sauce               0
Salsa.1             0
Cilantro            0
Onion               0
Taquito             0
Pineapple           0
Ham                 0
Chile relleno       0
Nopales             0
Lobster             0
Queso             298
Egg                 0
Mushroom            0
Bacon               0
Sushi               0
Avocado             0
Corn                0
Zucchini            0
Great               0
Year                0
dtype: int64

In [ ]:
# Create wrangle function
def wrangle(df):
  train.drop(['Great'], axis = 1, inplace=True)
  return df

# Wrangle feature matrix
X = wrangle(train)

# Separate labels from feature matrix
y = test.pop('Great')

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
X.shape, y.shape

((298, 59), (38,))

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, 
                                                  random_state=42)

print(X.shape)
print(X_train.shape)
print(X_val.shape)

# Check that training and validation contain all observations from X
assert X.shape[0] == X__train.shape[0] + X_val.shape[0]

ValueError: ignored

In [ ]:
# Check that feature matrices have same number of obersevations as labels
assert X__train.shape[0] == len(y__train)
assert X__val.shape[0] == len(y__val)

In [ ]:
'''Similar score or 58% as the Majority Class Baseline.

In [ ]:
y__train.value_counts(normalize=True)

Model 2

In [ ]:
# Instantiate pipeline with steps
log_model = Pipeline([
                      ('ohe', OneHotEncoder(cols=['Cost', 'Hunger','Google','Yelp'])),
                      ('imputer', SimpleImputer()),
                      ('classifier', LogisticRegressionCV())

])

In [ ]:
X__train

In [ ]:
y_train

In [ ]:
# Fit model on training data
log_model.fit(X__train, y__train);

In [ ]:
# Check permance metric (accuracy) on test set
print('Training Accuracy:', log_model.score(X_train, y_train))
print('Validation Accuracy:', log_model.score(X_val, y_val))

#4) Get your model's validation accuracy. (Multiple times if you try multiple iterations.) Get your model's test accuracy. (One time, at the end.)

In [ ]:
encoder = OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)
X_test_encoded = encoder.transform(X_test)

In [ ]:
X_train_encoded.head()

In [ ]:
imputer = SimpleImputer()
X_train_imputed= imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)
X_test_imputed = imputer.transform(X_test_encoded)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)
X_test_scaled = scaler.transform(X_test_imputed)

In [ ]:
y_train.value_counts(normalize=True)

In [ ]:
#Higher than baseline of 59%

In [ ]:
model = LogisticRegressionCV(cv=5, n_jobs=-1, random_state=42)
model.fit(X_train_scaled, y_train)
print('Validation Accuracy', model.score(X_val_scaled, y_val))

In [ ]:
print('Test Accuracy', model.score(X_test_scaled, y_test))

#Dondre' After Hours Study Session DS 211 Notes
Instructor:____________________